name: FactionMasterInvitationImprove
author: ShockedPlot7560
version: 1.1.0
api: 3.17.7
main: ShockedPlot7560\FactionMasterInvitationImprove\Main
depend: ["FactionMaster"]
virions: ["libFormAPI"]
description: "Extension which improve invitation system of FactionMaster"
